In [1]:
import numpy as np
x=np.arange(40)
print("x=",x)
print('\n')
print("\n")
y=x.reshape(10,4)
print("y=",y)

x= [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]




y= [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]


## import numpy as np

a=int(input("Enter number of rows:"))
b=int(input("Enter number of columns:"))
for i in range(a):
    for j in range(b):
        x=int(input("Enter the element:"))
        arr[i,j]=x
print("arr=",arr)